#!/usr/bin/env python3
"""Compile the fixed capture corpus; no printer access, extraction or fitting.

Run from any directory. --check verifies checked-in tables without writing them.
Capture provenance: zpl/assets/README.md and the named ZD621 regression fixtures.
"""
import argparse
import json
from pathlib import Path


def compile_data(source):
    assert source['schema'] == 'zpl-captured-strikes' and source['version'] == 1
    captures = {c['name']: c for c in source['captures']}
    metrics, offsets, bits = [], [], bytearray()
    record_ids, bit_offsets, maps, strikes, key_arrays = {}, {}, {}, [], {}
    lines = ['// Generated by data/compile_captures.py; do not edit.',
             'use crate::{captures::{Capture, Strike}, collection::Pool};']

    def record(g):
        _, advance, left, top, width, height, bitmap = g
        assert 0 <= advance <= 65535 and -32768 <= left <= 32767 and -32768 <= top <= 32767
        assert 0 <= width <= 4096 and 0 <= height <= 4096
        payload = bytes.fromhex(bitmap)
        assert len(payload) == ((width + 7) // 8) * height
        key = (advance, left, top, width, height, payload)
        if key not in record_ids:
            if payload not in bit_offsets:
                bit_offsets[payload] = len(bits)
                bits.extend(payload)
            record_ids[key] = len(metrics)
            assert len(metrics) < 65535
            metrics.append([advance, left & 65535, top & 65535, width, height])
            offsets.append(bit_offsets[payload])
        return record_ids[key]

    def strike(c, glyphs):
        items = sorted(glyphs.items())
        key = tuple((k, record(g)) for k, g in items)
        keys = tuple(k for k, _ in key)
        if keys not in key_arrays:
            key_arrays[keys] = len(key_arrays)
            lines.append(f'static KEYS_{key_arrays[keys]}: &[u32] = &{list(keys)};')
        key_id = key_arrays[keys]
        if key not in maps:
            n = len(maps)
            maps[key] = n
            lines.append(f'static RECORDS_{n}: &[u16] = &{[r for _, r in key]};')
        n = maps[key]
        identity = (c['font'], c['height'], c['width'], c['dpi'], key_id, n)
        if identity not in strikes:
            strikes.append(identity)
        return strikes.index(identity)

    def glyphs(c):
        result = {g[0]: g for g in c['glyphs']}
        assert len(result) == len(c['glyphs'])
        return result

    raw = []
    for c in source['captures']:
        raw.append((c, strike(c, glyphs(c))))

    def capture(name):
        return captures.get(name + '.zbf')

    def enriched(name):
        c = captures[name]
        gs = glyphs(c)
        prefix = f"font{c['font']}-{c['height']}-{c['width']}"
        supplements = []
        if name == 'font0-32.zbf':
            supplements.append(('font0-32-latin1', False))
        supplements.extend([(prefix + '-hyphen', False), (prefix + '-cent', False)])
        if (c['font'], c['height'], c['width']) == ('0', 32, 0):
            supplements.extend((prefix + '-' + suffix, True) for suffix in ['hebrew', 'missing'])
        if (c['font'], c['height'], c['width']) == ('0', 40, 24):
            supplements.extend((prefix + '-' + suffix, True) for suffix in
                               ['hebrew', 'extended', 'missing', 'conformance', 'controls'])
        for name, non_ascii in supplements:
            extra = capture(name)
            if extra:
                for k, g in glyphs(extra).items():
                    if not non_ascii or k > 126:
                        gs.setdefault(k, g)
        return c, gs

    variants = []
    # Flags: independently selectable legacy backslash, PA1, native ESC/DEL.
    # ^CI pp.156–159, ^PA p.315. Captures/precedence match the original renderer.
    for flags in range(8):
        faces = []
        for name in source['strike_order'] + ['font0-32.zbf']:
            c, gs = enriched(name)
            prefix = f"font{c['font']}-{c['height']}-{c['width']}"
            if flags & 1:
                extra = capture(prefix + '-legacy-backslash')
                if extra:
                    gs[92] = extra['glyphs'][0]
                elif c['font'] == '0':
                    gs.pop(92, None)
            if flags & 2:
                extra = capture(prefix + '-default-glyph')
                if extra:
                    gs.update({k: g for k, g in glyphs(extra).items() if k > 126})
            if flags & 4:
                extra = capture(prefix + '-legacy-controls' + ('-default' if flags & 2 else ''))
                if extra:
                    gs.update(glyphs(extra))
            faces.append(strike(c, gs))
        variants.append(faces)
    retail = [strike(captures[n], glyphs(captures[n])) for n in
              ['font0-25-14-retail.zbf', 'font0-32-0-retail.zbf']]
    lines.append(f'static METRICS: &[[u16; 5]] = &{metrics};')
    lines.append(f'static OFFSETS: &[u32] = &{offsets};')
    lines.append('static POOL: Pool = Pool { metrics: METRICS, offsets: OFFSETS, bits: include_bytes!("captures.bin") };')
    for i, (font, height, width, dpi, key_id, n) in enumerate(strikes):
        lines.append(f'static STRIKE_{i}: Strike = Strike {{ font: {font!r}, height: {height}, width: {width}, dpi: {dpi}, keys: KEYS_{key_id}, records: RECORDS_{n}, pool: &POOL }};')
    lines.append('pub static CAPTURES: &[Capture] = &[')
    for c, i in raw:
        lines.append(f'Capture {{ name: "{c["name"]}", legacy_format: {c["legacy_format"]}, sha256: "{c["sha256"]}", strike: &STRIKE_{i} }},')
    lines.append('];')
    lines.append('pub static VARIANTS: [&[&Strike]; 8] = [')
    for faces in variants:
        lines.append('&[' + ','.join(f'&STRIKE_{i}' for i in faces) + '],')
    lines.append('];')
    lines.append('pub static RETAIL: &[&Strike] = &[' + ','.join(f'&STRIKE_{i}' for i in retail) + '];')
    # Keep generated tables independent of rustfmt versions.
    rust = '\n'.join(lines) + '\n'
    rust = '// @generated\n#[rustfmt::skip]\nmod data {\n' + rust + '}\npub use data::{CAPTURES, RETAIL, VARIANTS};\n'
    return rust.encode(), bytes(bits), len(metrics), len(maps)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    source = json.loads((root / 'data/captures.json').read_text())
    rust, bitmap, records, maps = compile_data(source)
    for name, data in [('captures.rs', rust), ('captures.bin', bitmap)]:
        target = root / 'src/zd621' / name
        if args.check:
            assert target.read_bytes() == data, f'{target} requires regeneration'
        else:
            target.write_bytes(data)
    print(f'{len(source["captures"])} captures, {records} shared records, {maps} maps, {len(bitmap)} bitmap bytes')


if __name__ == '__main__':
    main()
