[package]
name = "zpl-c"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish = false
description = "C bindings for the local ZPL parser and renderer"
repository = "https://github.com/codyps/zpl"
readme = "README.md"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
zpl = { version = "0.2.0", path = "../zpl" }
