#!/usr/bin/env python3
"""Generate C configuration layouts from native fields, with no build dependency.
Run with --check in CI. Unsupported native types deliberately fail generation.
"""
import argparse
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
types = {
    'bool': ('u8', 'uint8_t'), 'u8': ('u8', 'uint8_t'),
    'u32': ('u32', 'uint32_t'), 'u64': ('u64', 'uint64_t'),
    'usize': ('usize', 'size_t'), 'f64': ('f64', 'double'),
    'Option<u32>': ('ZplOptionalU32', 'ZplOptionalU32'),
    'Option<u16>': ('ZplOptionalU16', 'ZplOptionalU16'),
    'Option<[u16; 3]>': ('ZplOptionalFileId', 'ZplOptionalFileId'),
}
rust = '// Generated by generate-config.py; do not edit.\n'
header = '''/* Generated by generate-config.py; do not edit. */
#ifndef ZPL_CONFIG_H
#define ZPL_CONFIG_H
#include <stddef.h>
#include <stdint.h>
/* Optional values: present must be 0 (None) or 1 (Some). */
typedef struct { uint8_t present; uint32_t value; } ZplOptionalU32;
typedef struct { uint8_t present; uint16_t value; } ZplOptionalU16;
typedef struct { uint8_t present; uint16_t value[3]; } ZplOptionalFileId;
'''
for name, native, path, struct in [
    ('ZplCompatibility', 'zpl::render::compatibility::Compatibility', 'render/compatibility.rs', 'Compatibility'),
    ('ZplRenderLimits', 'zpl::render::Limits', 'render/limits.rs', 'Limits'),
    ('ZplOutputLimits', 'zpl::output::Limits', 'output/limits.rs', 'Limits'),
    ('ZplSyntax', 'zpl::parse::Syntax', 'parse.rs', 'Syntax'),
]:
    text = (root.parent / 'zpl/src' / path).read_text()
    body = text.split('pub struct ' + struct + ' {', 1)[1].split('\n}', 1)[0]
    fields = re.findall(r'^    pub (\w+): ([^\n]+),$', body, re.M)
    assert fields, path
    rust += f'configuration!({name}, {native}, {{\n'
    header += f'typedef struct {name} {{\n'
    for field, ty in fields:
        rt, ct = types[ty]
        rust += f'    {field}: {rt},\n'
        header += f'    {ct} {field};\n'
    rust += '});\n'
    header += f'}} {name};\n'
header += '''typedef struct ZplOptions {
    uint32_t width;
    uint32_t height;
    uint32_t dpi;
    ZplCompatibility compatibility;
} ZplOptions;
#endif
'''
for path, content in [('src/config_fields.rs', rust), ('include/zpl_config.h', header)]:
    destination = root / path
    if args.check:
        if destination.read_text() != content:
            raise SystemExit(f'{destination} is stale; run zpl-c/generate-config.py')
    else:
        destination.write_text(content)
