//! Compact native tables: deduplicate records and payloads separately, trim the
//! key range, and densely pack bits across row edges.
use super::model::*;
use eyre::{ensure, Result};
use serde_json::json;
use std::{collections::BTreeMap, fmt::Write, fs, path::Path};

pub fn compile(document: &Document, out: &Path) -> Result<()> {
    document.validate()?;
    ensure!(!out.exists(), "output exists: {}", out.display());
    let first = document
        .fonts
        .iter()
        .flat_map(|f| &f.glyphs)
        .map(|g| g.key)
        .min()
        .unwrap();
    let last = document
        .fonts
        .iter()
        .flat_map(|f| &f.glyphs)
        .map(|g| g.key)
        .max()
        .unwrap();
    let mut records = BTreeMap::new();
    let mut payloads = BTreeMap::new();
    let mut metrics = Vec::new();
    let mut offsets = Vec::new();
    let mut bits = Vec::new();
    let mut tables = Vec::new();
    for f in &document.fonts {
        let mut table = vec![u16::MAX; usize::from(last - first) + 1];
        for g in &f.glyphs {
            let m = [
                u8::try_from(g.advance)?,
                i8::try_from(g.left)? as u8,
                i8::try_from(g.top)? as u8,
                u8::try_from(g.width)?,
                u8::try_from(g.height)?,
            ];
            let payload = g.dense();
            let key = (m, payload.clone());
            let id = if let Some(&id) = records.get(&key) {
                id
            } else {
                ensure!(
                    metrics.len() < usize::from(u16::MAX),
                    "too many unique glyphs"
                );
                let offset = if let Some(&offset) = payloads.get(&payload) {
                    offset
                } else {
                    let offset = u32::try_from(bits.len())?;
                    bits.extend_from_slice(&payload);
                    payloads.insert(payload, offset);
                    offset
                };
                let id = metrics.len() as u16;
                metrics.push(m);
                offsets.push(offset);
                records.insert(key, id);
                id
            };
            table[usize::from(g.key - first)] = id;
        }
        tables.push(table);
    }
    let mut rust = String::from("// Generated by zpl-font-extract compile. Do not edit.\nuse zpl_bitmap_fonts::{Font, Mapping, Metrics, Pool};\n");
    writeln!(rust, "#[rustfmt::skip]\nstatic POOL: Pool = Pool {{ metrics: &{metrics:?}, offsets: &{offsets:?}, bits: include_bytes!(\"bitmaps.bin\") }};")?;
    writeln!(rust, "#[rustfmt::skip]\npub static FONTS: &[Font] = &[")?;
    for (f, table) in document.fonts.iter().zip(tables) {
        let m = &f.metrics;
        let mapping = if document.mapping.kind == "ci0-source" {
            "Mapping::Ci0Source".into()
        } else {
            format!(
                "Mapping::Input {{ encoding: {} }}",
                document.mapping.encoding
            )
        };
        writeln!(rust,"Font {{ name: {:?}, mapping: {mapping}, metrics: Metrics {{ cell_height: {}, cell_width: {}, baseline: {}, space_advance: {} }}, first_key: {first}, lookup: &{table:?}, pool: &POOL }},",f.name,m.cell_height,m.cell_width,m.baseline,m.space_advance)?;
    }
    rust.push_str("];\npub fn font_by_name(name: &str) -> Option<&'static Font> {\n    FONTS.iter().find(|f| f.name == name)\n}\n");
    let size = document.fonts.len() * 8
        + document.fonts.len() * (usize::from(last - first) + 1) * 2
        + metrics.len() * 9
        + bits.len();
    let catalog = json!({"schema":"zpl-compact-fonts-v1", "source_content_sha256":document.content_hash()?, "unique_records":metrics.len(), "unique_payloads":payloads.len(), "data_bytes":size, "bitmaps_sha256":hash(&bits), "module_sha256":hash(rust.as_bytes())});
    fs::create_dir_all(out)?;
    fs::write(out.join("fonts.rs"), rust)?;
    fs::write(out.join("bitmaps.bin"), bits)?;
    write_json(&out.join("catalog.json"), &catalog)?;
    Ok(())
}
