[package]
name = "zebra-http-api"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
htmlize = { version = "1.0.5", features = ["unescape"] }
memchr = "2.7.4"
reqwest.workspace = true

[dev-dependencies]
raster-diff = { version = "0.1.0", path = "../raster-diff" }
clap = { version = "4.5.18", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
zpl = { version = "0.1.0", path = "../zpl" }
serde_json = "1.0.128"
