[package]
name = "zebra-http-api"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish = false

[dependencies]
getrandom = "0.4.3"
eyre = "0.6.14"
htmlize = { version = "1.1.0", features = ["unescape"] }
memchr = "2.8.3"
# Form and query encoding are opt-in in Reqwest 0.13.
# https://docs.rs/reqwest/0.13/reqwest/#optional-features
reqwest = { workspace = true, features = ["form", "query"] }

[dev-dependencies]
sha2 = "0.11.0"
raster-diff = { version = "0.1.1", path = "../raster-diff" }
clap = { version = "4.6.7", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
zpl = { version = "0.3.0", path = "../zpl" }
serde_json = "1.0.151"
