//! Deterministic compact tables, deduplicating metrics, glyph bytes and candidate sets.
use super::*;
use serde_json::json;
use std::{collections::BTreeMap, fmt::Write, fs};
pub fn compile(c: &Collection, out: &Path) -> Result<()> {
    c.validate()?;
    ensure!(!out.exists(), "output exists");
    let mut pool = BTreeMap::new();
    let mut payloads = BTreeMap::new();
    let mut metrics = vec![];
    let mut offsets = vec![];
    let mut bits = vec![];
    let mut fonts = vec![];
    for f in &c.fonts {
        let mut indices = vec![];
        for r in &f.records {
            let m = [
                r.advance,
                r.left as u16,
                r.top as u16,
                r.width,
                r.height,
                r.flags,
            ];
            let bytes = unhex(&r.bitmap_hex)?;
            let key = (m, bytes.clone());
            let index = if let Some(&i) = pool.get(&key) {
                i
            } else {
                let i = u16::try_from(metrics.len())?;
                let off = if let Some(&off) = payloads.get(&bytes) {
                    off
                } else {
                    let off = u32::try_from(bits.len())?;
                    bits.extend_from_slice(&bytes);
                    payloads.insert(bytes, off);
                    off
                };
                metrics.push(m);
                offsets.push(off);
                pool.insert(key, i);
                i
            };
            indices.push(index);
        }
        fonts.push(indices);
    }
    let mut rust=String::from("// Generated by zpl-font-extract collection compile.\nuse zpl_bitmap_fonts::collection::{Font,Pool,Map,Encoding,CandidateCodePage};\n");
    writeln!(rust,"#[rustfmt::skip]\nstatic POOL:Pool=Pool{{metrics:&{metrics:?},offsets:&{offsets:?},bits:include_bytes!(\"bitmaps.bin\")}};")?;
    let mut candidate_pool = vec![];
    let mut sets = BTreeMap::new();
    let mut map_names = vec![];
    let mut shared_maps = BTreeMap::new();
    let mut map_bytes = 0usize;
    for f in &c.fonts {
        let mut names = vec![];
        for m in &f.encodings {
            let inputs = m.entries.iter().map(|e| e.input).collect::<Vec<_>>();
            let mut spans = vec![];
            let statuses = m
                .entries
                .iter()
                .map(|e| match e.status {
                    Status::Matched => 0u8,
                    Status::BlankUnresolved => 1,
                    Status::Unmatched => 2,
                    Status::FilenameFallback => 3,
                    Status::UnverifiedCandidate => 4,
                })
                .collect::<Vec<_>>();
            for e in &m.entries {
                let start = if let Some(&off) = sets.get(&e.candidates) {
                    off
                } else {
                    let off = u32::try_from(candidate_pool.len())?;
                    candidate_pool.extend_from_slice(&e.candidates);
                    sets.insert(e.candidates.clone(), off);
                    off
                };
                spans.push([start, u32::try_from(e.candidates.len())?]);
            }
            let key = (inputs.clone(), spans.clone(), statuses.clone());
            let number = if let Some(&i) = shared_maps.get(&key) {
                i
            } else {
                let i = shared_maps.len();
                shared_maps.insert(key, i);
                map_bytes += inputs.len() * 13;
                writeln!(rust,"#[rustfmt::skip]\nstatic INPUTS_{i}:&[u32]=&{inputs:?};\n#[rustfmt::skip]\nstatic SPANS_{i}:&[[u32;2]]=&{spans:?};\n#[rustfmt::skip]\nstatic STATUS_{i}:&[u8]=&{statuses:?};")?;
                i
            };
            let encoding = match m.encoding {
                Encoding::Input { ci } => format!("Encoding::Input{{ci:{ci}}}"),
                Encoding::Ci0Source => "Encoding::Ci0Source".into(),
                Encoding::CandidateCharacters => "Encoding::CandidateCharacters".into(),
            };
            names.push(format!("Map{{encoding:{encoding},inputs:INPUTS_{number},spans:SPANS_{number},statuses:STATUS_{number},candidates:CANDIDATES}}"));
        }
        map_names.push(names.join(","));
    }
    writeln!(rust,"#[rustfmt::skip]\nstatic CANDIDATES:&[u16]=&{candidate_pool:?};\n#[rustfmt::skip]\npub static FONTS:&[Font]=&[")?;
    let mut lookup_bytes = 0;
    for ((f, indices), maps) in c.fonts.iter().zip(fonts).zip(map_names) {
        let ids = f.records.iter().map(|r| r.id).collect::<Vec<_>>();
        lookup_bytes += 116 + ids.len() * 4 + f.zero_record_slots.len() * 2;
        writeln!(rust,"Font{{name:{:?},header:&{:?},slot_count:{},zero_record_slots:&{:?},ids:&{ids:?},records:&{indices:?},pool:&POOL,encodings:&[{maps}]}},",f.name,unhex(&f.header_hex)?,f.slot_count,f.zero_record_slots)?;
    }
    rust.push_str("];\npub fn font_by_name(name:&str)->Option<&'static Font>{FONTS.iter().find(|f|f.name==name)}\n");
    writeln!(
        rust,
        "#[rustfmt::skip]\npub static CANDIDATE_CODE_PAGES:&[CandidateCodePage]=&["
    )?;
    for page in &c.candidate_code_pages {
        writeln!(
            rust,
            "CandidateCodePage{{ci:{},byte_to_character:&{:?}}},",
            page.ci, page.byte_to_character
        )?;
    }
    rust.push_str("];\n");
    let catalog = json!({"schema":"zpl-compact-collection-v2","source_content_sha256":c.content_sha256,"unique_records":metrics.len(),"unique_payloads":payloads.len(),"unique_maps":shared_maps.len(),"coverage":c.coverage,"candidate_code_pages":c.candidate_code_pages.len(),"array_bytes":c.candidate_code_pages.len()*512+bits.len()+metrics.len()*16+map_bytes+candidate_pool.len()*2+lookup_bytes,"bitmaps_sha256":hash(&bits),"module_sha256":hash(rust.as_bytes())});
    fs::create_dir_all(out)?;
    fs::write(out.join("fonts.rs"), rust)?;
    fs::write(out.join("bitmaps.bin"), bits)?;
    crate::automatic::model::write_json(&out.join("catalog.json"), &catalog)?;
    Ok(())
}
