[package]
name = "zpl"
version = "0.3.0"
edition = "2021"
description = "A high accuracy ZPL renderer"
license.workspace = true
readme = "README.md"
repository = "https://github.com/codyps/zpl"
documentation = "https://docs.rs/zpl"
include = ["src/**", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
zpl-bitmap-fonts = { version = "0.1.0", path = "../zpl-bitmap-fonts", features = [
    "zd621",
] }
encoding_rs = "0.8.41"
unicode-normalization = "0.1.25"
unicode-bidi = "0.3.18"
raster-diff = { version = "0.1.1", path = "../raster-diff" }

[dev-dependencies]
serde_json = "1.0.151"
sha2 = "0.11.0"
rxing = { version = "0.9.3", default-features = false, features = [
    "decoders",
    "full_barcode_format_support",
    "multi_barcode_readers",
    "encoding_rs",
] }
anyd = { version = "0.2.0", default-features = false, features = [
    "std",
    "decode",
    "pdf417",
    "code11",
    "code49",
    "codablockf",
    "msi",
    "twoof5",
    "postal",
    "maxicode",
    "databar",
] }
lopdf = "0.45.0"
reqwest = "0.13.5"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.6"
