[package]
name = "zpl_elixir"
version = "0.3.0"
edition = "2021"
license.workspace = true
publish = false
description = "Elixir bindings for the local ZPL parser and renderer"
repository = "https://github.com/codyps/zpl"

[lib]
name = "zpl_elixir"
crate-type = ["cdylib", "rlib"]

[dependencies]
rustler = "0.38.0"
zpl = { version = "0.3.0", path = "../zpl" }
