#!/usr/bin/env python3
"""Reproduce the Linux prototype comparison. Requires Go, Rust/Wasm, C compiler.
No network/printer rendering is used. Downloads are pinned Go modules/tool only.
Local binaries, oracle outputs, logs and caches are ignored.
The generated Wasm/Go artifacts are shipped and regenerated by this runner.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import shutil
import struct
import subprocess
import time
import tempfile

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
ART = HERE / "artifacts"
parser = argparse.ArgumentParser()
parser.add_argument("--skip-build", action="store_true")
parser.add_argument("--measure-only", action="store_true", help="reuse validated binaries and build results")
parser.add_argument("--iterations", type=int, default=20)
args = parser.parse_args()
ART.mkdir(exist_ok=True)
env = os.environ.copy()
TARGET = Path(env.get("CARGO_TARGET_DIR", ROOT / "target/go-prototype/rust")).resolve()
env["CARGO_TARGET_DIR"] = str(TARGET)
LIB = TARGET / "release/libzpl_go_prototype.so"
env["ZPL_GO_LIBRARY"] = str(LIB)
env["CGO_LDFLAGS"] = f"-L{LIB.parent} -Wl,-rpath,{LIB.parent}"
env["GOMAXPROCS"] = "2"
report = {"platform": platform.platform(), "machine": platform.machine(), "cpu": next((line.split(':',1)[1].strip() for line in Path('/proc/cpuinfo').read_text().splitlines() if line.startswith('model name')), ''), "gomaxprocs": 2, "builds": {}, "backends": {}}

def run(name, cmd, cwd=HERE, overrides=None, timeout=600, allowed_failure=False):
    actual = env | (overrides or {})
    start = time.perf_counter()
    result = subprocess.run(cmd, cwd=cwd, env=actual, capture_output=True, timeout=timeout)
    elapsed = time.perf_counter()-start
    (ART / f"{name}.stdout").write_bytes(result.stdout)
    (ART / f"{name}.stderr").write_bytes(result.stderr)
    print(f"{name}: {elapsed:.3f}s exit={result.returncode}", flush=True)
    if result.returncode and not allowed_failure:
        raise RuntimeError(f"{name} failed; see artifacts/{name}.stderr")
    return {"seconds": elapsed, "exit": result.returncode, "command": cmd}

def save():
    (ART / "report.json").write_text(json.dumps(report, indent=2)+"\n")


def measure():
    # All builds and tests finish before measurements. Rotate execution order
    # between fresh processes; retain every sample, including slower batches.
    names = list(report["backends"])
    for entry in report["backends"].values():
        entry.pop("bench", None)  # Discard the preliminary single-process sample.
    for name in names:
        report["backends"][name]["cold"] = []
        report["backends"][name]["bench_processes"] = []
    for trial in range(5):
        for name in names[trial % len(names):] + names[:trial % len(names)]:
            label = f"final-cold-{name}-{trial}"
            timing = run(label, [str(ART / ("probe-" + name)), "-cold"])
            timing |= json.loads((ART / (label + ".stdout")).read_text())
            report["backends"][name]["cold"].append(timing)
    for trial in range(3):
        for name in names[trial % len(names):] + names[:trial % len(names)]:
            label = f"final-bench-{name}-{trial}"
            run(label, [str(ART / ("probe-" + name)), "-bench", "-n", str(args.iterations)])
            report["backends"][name]["bench_processes"].append(json.loads((ART / (label + ".stdout")).read_text()))
        save()
    report["measurement"] = {"iterations_per_batch": args.iterations, "batches_per_process": 5, "processes": 3, "cold_processes": 5, "note": "Sequential execution after all task builds/tests; rotated backend order. Cold processes use warm OS file caches, no wazero compilation cache."}
    save()

if args.measure_only:
    report = json.loads((ART / "report.json").read_text())
    measure()
    raise SystemExit(0)

for tool in ["go", "rustc", "cargo"]:
    report[tool] = subprocess.check_output([tool, "version" if tool=="go" else "--version"], env=env, text=True).strip()
report["commit"] = subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip()
if not args.skip_build:
    report["builds"]["native"] = run("build-native", ["cargo","build","--locked","--release","-p","zpl-go-prototype","--lib","--example","oracle"], ROOT)
    report["builds"]["guest-and-translation"] = run("generate", ["python3", "generate.py"])

# Fixed synthetic inputs supplement existing repository capture inputs. They test
# interop parity, not new printer accuracy claims. GFB follows render.rs regressions.
sources = {
 "boxes": b"^XA^FO10,10^GB200,100,3^FS^FO30,30^GB80,50,8,W^FS^FO20,20^FR^GB100,40,4^FS^XZ",
 "text": "^XA^CI28^FO10,10^A0N,32,32^FDHello, Go! café^FS^FO10,65^ABN,18,10^FD0123456789^FS^XZ".encode(),
 "dense": ("^XA"+"".join(f"^FO{10+(i%4)*125},{10+(i//4)*35}^A0N,20,18^FDSKU {i:04d}^FS" for i in range(48))+"^XZ").encode(),
 "barcodes": b"^XA^FO10,10^BY2^BCN,60,N,N,N^FD123456789012^FS^FO10,90^BQN,2,3^FDLA,Go bridge 123^FS^XZ",
 "curves": b"^XA^FO20,20^GC100,3^FS^FO150,20^GE120,80,4^FS^FO20,150^GB200,100,4,B,6^FS^XZ",
 "rotated": b"^XA^FO60,40^A0R,30,24^FDROTATE^FS^FO180,120^A0I,30,24^FDFLIP^FS^XZ",
 "binary": b"^XA^FO10,10^GFB,8,8,1,\xff\x81\x00\x5e\x7e\x2c\x80\xff^FS^XZ",
 "graphic": b"^XA^FO10,10^GFA,8192,8192,32," + b"AA55"*4096 + b"^FS^XZ",
 "multipage": b"^XA^FO10,10^GB100,100,2^FS^XZ^XA^FO10,10^A0N,24,24^FDPage two^FS^XZ",
 "empty": b"",
 "invalid": b"^XA^GFA,2,2,1,:B64:/4E=:0000^FS^XZ",
}
inputs = ART / "inputs"
inputs.mkdir(exist_ok=True)
for name,source in sources.items(): (inputs / f"{name}.zpl").write_bytes(source)
# Preserve capture sources/provenance in their original directory.
for name,filename in [("capture-qr","barcode-qr.zpl"),("capture-code128","barcode-code128.zpl")]:
    shutil.copyfile(ROOT / "zpl/tests/fixtures/zq610-plus-v1" / filename, inputs / f"{name}.zpl")
    sources[name] = (inputs / f"{name}.zpl").read_bytes()
cases=[]
for name in sources:
    for profile in range(3):
        for fmt in range(4):
            c={"Name":f"{name}-p{profile}-f{fmt}","Input":f"inputs/{name}.zpl","Format":fmt,"Profile":profile,"Width":512,"Height":512,"Status":2 if name in ["empty","invalid"] else 0,"Bench":profile==0 and ((fmt==0 and name in ["boxes","text","dense","barcodes","graphic"]) or (name=="dense" and fmt==1) or (name=="multipage" and fmt==2))}
            cases.append(c)
for name,field,value in [("bad-format","Format",99),("bad-profile","Profile",99),("zero-width","Width",0)]:
    c={"Name":name,"Input":"inputs/boxes.zpl","Format":0,"Profile":0,"Width":512,"Height":512,"Status":1,"Bench":False};c[field]=value;cases.append(c)
(ART / "oracle").mkdir(exist_ok=True)
for c in cases:
    c["Expected"]="oracle/"+c["Name"]+".bin"
    subprocess.run([str(TARGET / "release/examples/oracle"),str(ART/c["Input"]),str(ART/c["Expected"]),str(c["Format"]),str(c["Profile"]),str(c["Width"]),str(c["Height"])],env=env,check=True)
    data=(ART/c["Expected"]).read_bytes()
    status=struct.unpack_from('<I',data,4)[0]
    if status!=c["Status"]:raise RuntimeError(f"oracle {c['Name']} unexpected status={status}: {data[32:200]!r}")
    c["OracleSHA256"]=hashlib.sha256(data).hexdigest()
(ART / "cases.json").write_text(json.dumps(cases,indent=2)+"\n")
report["cases"]=len(cases)
report["wasm_sha256"]=hashlib.sha256((HERE/"guest.wasm").read_bytes()).hexdigest()
report["wasm_bytes"]=(HERE/"guest.wasm").stat().st_size
report["library_bytes"]=LIB.stat().st_size
report["generated_go_bytes"]=(HERE/"internal/translated/module.go").stat().st_size
save()
for backend in ["cgo","purego","wazero","wasm2go"]:
    settings={"CGO_ENABLED":"1" if backend=="cgo" else "0"}
    tag="backend_"+backend
    exe=ART / ("probe-"+backend)
    entry=report["backends"][backend]={}
    if not args.skip_build:
        # Separate initially empty caches measure consumer compilation (including
        # stdlib), excluding dependency downloads and Rust/translation production.
        settings["GOCACHE"]=tempfile.mkdtemp(prefix="cache-"+backend+"-", dir=ART)
        entry["build"]=run("build-"+backend,["go","build","-trimpath","-ldflags=-s -w","-tags",tag,"-o",str(exe),"./cmd/probe"],overrides=settings)
        entry["rebuild"]=run("rebuild-"+backend,["go","build","-trimpath","-ldflags=-s -w","-tags",tag,"-o",str(exe),"./cmd/probe"],overrides=settings)
    entry["binary_bytes"]=exe.stat().st_size
    entry["test"]=run("test-"+backend,["go","test","-count=1","-tags",tag,"."],overrides=settings,allowed_failure=True)
    check=run("check-"+backend,[str(exe)],overrides=settings,allowed_failure=True)
    entry["correctness"]=json.loads((ART / ("check-"+backend+".stdout")).read_text()) if (ART / ("check-"+backend+".stdout")).stat().st_size else check
    save()
if any(b["test"]["exit"] or b["correctness"].get("failed", b["correctness"].get("exit", 0)) for b in report["backends"].values()):
    raise SystemExit("Correctness failed; see report.json. No performance run.")
measure()
print("Results: zpl-go/artifacts/report.json",flush=True)
